services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rodrigodittrich/laravel
    container_name: laravel
    working_dir: /var/www
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/app-laravel