services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rodrigodittrich/laravel
    container_name: laravel
    working_dir: /var/www
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/app-laravel
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: